local keymap = require('vim.keymap').set

keymap('n', '<leader>dc', "<cmd>lua require'dap'.run_to_cursor()<cr>")
-- keymap('n', '', "<cmd>lua require'dapui'.eval(vim.fn.input '[Expression] > ')<cr>")
keymap('n', '<leader>db', "<cmd>lua require'dap'.set_breakpoint(vim.fn.input '[Condition] > ')<cr>")
keymap('n', '<leader>d', "<cmd>lua require'dapui'.toggle()<cr>")
-- keymap('n', '<leader>d', "<cmd>lua require'dapui'.open()<cr>")
-- keymap('n', '<leader>d', "<cmd>lua require'dapui'.close()<cr>")
-- keymap('n', '', "<cmd>lua require'dap'.step_back()<cr>")
keymap('n', '<F2>', "<cmd>lua require'dap'.continue()<cr>")
-- keymap('n', '', "<cmd>lua require'dap'.disconnect()<cr>")
-- keymap('n v', '', "<cmd>lua require'dapui'.eval()<cr>")
-- keymap('n', '', "<cmd>lua require'dap'.session()<cr>", "Get Session" })
keymap('n', '<leader>dk', "<cmd>lua require'dap.ui.widgets'.hover()<cr>")
-- keymap('n', '', "<cmd>lua require'dap.ui.widgets'.scopes()<cr>", "Scopes" })
keymap('n', '<F3>', "<cmd>lua require'dap'.step_into()<cr>")
keymap('n', '<F4>', "<cmd>lua require'dap'.step_over()<cr>")
keymap('n', '<F10>', "<cmd>lua require'dap'.pause()<cr>")
keymap('n', '<F12>', "<cmd>lua require'dapui'.close()<cr>")
keymap('n', '<leader>dr', "<cmd>lua require'dap'.repl.toggle()<cr>")
keymap('n', '<F1>', "<cmd>lua require'dap'.toggle_breakpoint()<cr>")
keymap('n', '<F11>', "<cmd>lua require'dap'.terminate()<cr>")
keymap('n', '<F5>', "<cmd>lua require'dap'.step_out()<cr>")
